import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "next-themes"
import ThemeToggleButton from "./components/theme-toggle-button"
import "@qnkur/segmented/fonts.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="absolute right-2 top-2">
            <ThemeToggleButton />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
